# example for: config/hubs_credentials.yaml
scihub:
  api_url: https://scihub.copernicus.eu/dhus
  user: otheruser
  password: testtest
apihub:
  api_url: https://apihub.copernicus.eu/apihub
  user: otheruser
  password: testtest
