version: "3.1"
services:
  copsi:
    image: "collaborativedhs/copsi:1.0.1"
    #container_name: copsi
    hostname: copsi
    #restart: always
    ports:
      - "8090:80"
    volumes:
      - copsi-config:/usr/local/apache2/htdocs/assets/config
      # uncomment the following line in case of deployment without proxy
      - /shared/copsi-html/index.html:/usr/local/apache2/htdocs/index.html    

volumes:
  copsi-config:
    driver_opts:
      type: "nfs"
      o: "addr=172.20.7.26,nolock,soft,rw"
      device: ":/shared/copsi-config/"

networks:
  default:
    external:
      name: collnetwork
