version: "3.8"
services:
  copsi:
    image: "collaborativedhs/copsi:3.0.1"
    hostname: copsi
    ports:
      - "8090:80"
    volumes:
      - type: volume
        source: copsi-config
        target: /usr/local/apache2/htdocs/assets/config
        volume:
          nocopy: true        
    # uncomment the following 3 lines in case of deployment without proxy          
    #configs:
    #  - source: copsi_index
    #    target: /usr/local/apache2/htdocs/index.html

    deploy:
      placement:
        constraints:
          - node.labels.copsi_tag == true
configs:
    copsi_index:
      file: ./data/copsi/html/index.html

volumes:
  copsi-config:
    driver_opts:
      type: "nfs"
      o: "addr=127.0.0.1,nolock,soft,rw"
      device: ":/shared/copsi-config/"

networks:
  default:
    external:
      name: collnetwork
