version: "3.8"
services:

  ingester:
    image: "gaeldockerhub/cdh-ingest:1.4.3"
    environment:
       CONF_FILE: /ingest/etc/database-conf-application.properties
    volumes:
       - /<path-to>/cdh-compose-1.4.3/ingest/logs/:/ingest/logs
       - <path-to-destination-folder>/error:/ingest/error
       - <path-to-destination-folder>/tmp:/ingest/tmp
       - <path-to-destination-product-folder>/:/ingest/folder1
    configs:
      - source: database-configuration-for-ingestion-properties
        target: /ingest/etc/database-conf-application.properties

    deploy:
      placement:
        constraints:
          - node.labels.gss_ingest_tag == true
configs:
  database-configuration-for-ingestion-properties:
    file: ./config/ingest/database-configuration-for-ingestion.properties

networks:
  default:
    external:
      name: collnetwork            
