version: "3.1"
services:
  catalogue:
    image: "gaeldockerhub/cdh-admin-api:1.2.0"
    ports:
     - 8082:8082
    volumes:
     - gss-admin-config:/admin-api/etc/application.properties

volumes:
  gss-admin-config:
    external: true

networks:
  default:
    external:
      name: collnetwork
