version: "3.1"
services:
  catalogue:
    image: "gaeldockerhub/cdh-catalogue:1.2.0"
    ports:
     - 8081:8081
    volumes:
     - ./config/catalogue/gss-catalogue.xml:/catalogue/etc/gss.xml
     - ./config/catalogue/application.properties:/catalogue/etc/application.properties
     - ./data/catalogue:/catalogue/hfs

networks:
  default:
    external:
      name: collnetwork
