version: "3.1"
services:
  producer:
    image: "gaeldockerhub/cdh-ingest:1.2.0"
    volumes:
     - ./config/ingest/gss-producer.xml:/ingest/etc/gss.xml
     - ./logs/ingest/producer:/ingest/logs 

  consumer:
    image: "gaeldockerhub/cdh-ingest:1.2.0"
    volumes:
    - ./config/ingest/gss-consumer.xml:/ingest/etc/gss.xml
    - ./data/ingest:/ingest/folder
    - ./data/ingest/error:/ingest/error
    - ./data/ingest/tmp:/ingest/tmp 
    - ./logs/ingest/consumer:/ingest/logs

networks:
  default:
    external:
      name: collnetwork
