version: "3.1"
services:
  catalogue:
    image: "gaeldockerhub/cdh-admin-api:1.2.0"
    ports:
     - 8082:8082
    volumes:
     - ./config/admin/application.properties:/admin-api/etc/application.properties

networks:
  default:
    external:
      name: collnetwork
