version: "3.8"
services:


  INGESTION-DAS-S1:
    image: "gaeldockerhub/cdh-ingest:1.4.3"
    environment:
       CONF_FILE: /ingest/etc/database-conf-application.properties
    volumes:
       - /data/GSS/cdh-compose-1.4.3/ingest/logs/:/ingest/logs
       - /mnt/ivvnas/2click_test/GSS/DESTINATION_FOLDER2/S1/error:/ingest/error
       - /mnt/ivvnas/2click_test/GSS/DESTINATION_FOLDER2/S1/tmp:/ingest/tmp
       - /mnt/ivvnas/2click_test/GSS/DESTINATION_FOLDER2/S1/:/ingest/folder1

    configs:
      - source: s1_application_properties
        target: /ingest/etc/database-conf-application.properties

    deploy:
      placement:
        constraints:
          - node.labels.gss_ingest_tag == true
configs:
  s1_application_properties:
    file: ./config/ingest/INGESTION_DAS_S1.properties

networks:
  default:
    external:
      name: collnetwork            
