version: '3.8'
services:
  esa_tf_scheduler:
    image: daskdev/dask:2023.3.2-py3.10
    ports:
      - target: 8786
        published: 8786
        protocol: tcp
        mode: host
      - target: 8787
        published: 8787
        protocol: tcp
        mode: host        
    command: dask scheduler
    deploy:
      placement:
        constraints:
          - node.labels.tf_tag == true

  esa_tf_restapi:
    image: ${ESA_REGISTRY_PATH:-collaborativedhs}/esa_tf_restapi:${ESA_TF_RELEASE:-latest}
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host        
    command: make serve PORT=8000 SCHEDULER="tcp://esa_tf_scheduler:8786"
    volumes:
      - tf-config:/config
      - tf-output:/output  
        #      - "${CONFIG_DIR:-./config}:/config"
        # - "${OUTPUT_DIR:-./output}:/output"
    environment:
      - ESA_TF_CONFIG_FILE=/config/esa_tf.config
      - FORWARDED_ALLOW_IPS=*
      - ROOT_PATH=${ROOT_PATH}
      - OUTPUT_DIR=/output
    deploy:
      placement:
        constraints:
          - node.labels.tf_tag == true

  esa_tf_worker:
    image: ${ESA_REGISTRY_PATH:-collaborativedhs}/esa_tf_worker:${ESA_TF_RELEASE:-latest}
    depends_on:
      - esa_tf_scheduler
    volumes:
      - tf-data:/data
      - tf-output:/output
      - tf-config:/config
      - tf-plugins:/plugins
      - tf-traces:/traces   
        #- "${DATA_DIR:-./data}:/data"
        #- "${OUTPUT_DIR:-./output}:/output"
        #- "${CONFIG_DIR:-./config}:/config"
        #- "${PLUGINS_DIR:-./plugins}:/plugins"
        #- "${TRACES_DIR:-./traces}:/traces"
    environment:
      - ESA_TF_CONFIG_FILE=/config/esa_tf.config
      - HUBS_CREDENTIALS_FILE=/config/hubs_credentials.yaml
      - TRACEABILITY_CONFIG_FILE=/config/traceability_config.yaml
      - KEY_FILE=/config/secret.txt
      - TRACETOOL_FILE=/opt/tracetool-1.2.4.jar
      - OUTPUT_DIR=/output
      - TRACES_DIR=/traces
      - OUTPUT_OWNER_ID=${OUTPUT_OWNER_ID:-0}
      - OUTPUT_GROUP_OWNER_ID=${OUTPUT_GROUP_OWNER_ID:-0}
      - TF_DEBUG=${TF_DEBUG:-0}
    command: "sh -c 'if \\[ -n \"$$(ls /plugins/* 2>/dev/null)\" \\]; then pip install /plugins/* ; fi &&\n       cd /opt/esa-tf-platform && \n       make dask-worker DASKFLAGS=\"tcp://esa_tf_scheduler:8786 --nworkers ${NPROCESSES:-8} --nthreads 1\"'\n"
    deploy:
      placement:
        constraints:
          - node.labels.tf_tag == true

  esa_tf_proxy:
    image: nginx:1.21.6
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
    volumes:
            #- ./nginx/templates:/etc/nginx/templates
            #- ./nginx/njs:/etc/nginx/njs
            #- ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - tf-nginx_templates:/etc/nginx/templates
      - tf-nginx_njs:/etc/nginx/njs
      - tf-logs:/var/log/nginx  
      - tf-output:/usr/share/nginx/html  
        #- "${LOGS:-./logs}:/var/log/nginx"
        #- "${OUTPUT_DIR:-./output}:/usr/share/nginx/html"
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    environment:
      - NGINX_HOST=_
      - NGINX_PORT=8080
      - APPLICATION_HOSTNAME=${APPLICATION_HOSTNAME}
      - APPLICATION_PROTO=${APPLICATION_PROTO}
      - OIDC_ACTIVE=${OIDC_ACTIVE}
      - OIDC_ROOT_URL=${OIDC_ROOT_URL}
      - REALM_NAME=${REALM_NAME}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - KEYCLOAK_HOST_HEADER=${KEYCLOAK_HOST_HEADER}
      - GUARD_ROLE=${GUARD_ROLE}
    deploy:
      placement:
        constraints:
          - node.labels.tf_tag == true

configs:
  nginx_conf:
    file:  /shared/tf-nginx/nginx.conf

volumes:
  tf-config:
    driver_opts:
      type: "nfs"
      o: "addr=172.20.7.25,nolock,soft,rw"
      device: ":/shared/tf-config/"
  tf-output:
    driver_opts:
      type: "nfs"
      o: "addr=172.20.7.25,nolock,soft,rw"
      device: ":/shared/tf-output/"
  tf-data:
    driver_opts:
      type: "nfs"
      o: "addr=172.20.7.25,nolock,soft,rw"
      device: ":/shared/tf-data/"
  tf-plugins:
    driver_opts:
      type: "nfs"
      o: "addr=172.20.7.25,nolock,soft,rw"
      device: ":/shared/tf-plugins/"
  tf-traces:
    driver_opts:
      type: "nfs"
      o: "addr=172.20.7.25,nolock,soft,rw"
      device: ":/shared/tf-traces/"
  tf-logs:
    driver_opts:
      type: "nfs"
      o: "addr=172.20.7.25,nolock,soft,rw"
      device: ":/shared/tf-logs/"
  tf-nginx_templates:
    driver_opts:
      type: "nfs"
      o: "addr=172.20.7.25,nolock,soft,rw"
      device: ":/shared/tf-nginx/templates"
  tf-nginx_njs:
    driver_opts:
      type: "nfs"
      o: "addr=172.20.7.25,nolock,soft,rw"
      device: ":/shared/tf-nginx/njs"
networks:
  default:
    external:
      name: collnetwork            
