version: '3.7'
services:
    sf-kb:
        image: openlink/virtuoso-opensource-7:latest
        container_name: kb
        environment:
            - DBA_PASSWORD=mysecret
        ports:
            - '1111:1111'
            - '8890:8890'
        volumes:
            - kb_db:/database
    dr-api:
        image: collaborativedhs/sf-datareceiver:v2.0
        container_name: dr
        ports:
            - '8088:8080'    
        volumes:
            - dr-api_logs:/logs       
    sf-api:
        image: collaborativedhs/semantic_framework:v2.3
        depends_on:
            - sf-kb
            - dr-api
        ports:
            - '8087:8080'    
        volumes:
            - /var/lib/docker/volumes/sf-config/_data/configuration.json:/config/configuration.json
            - sf-api_logs:/logs
            - /var/lib/docker/volumes/sf-config/_data/keycloak_configuration.json:/config/keycloak_configuration.json
        environment:
            - 'KB_ADDRESS=jdbc:virtuoso://sf-kb:1111'
            - 'KB_ADDRESS_REPO=http://sf-kb:8890/'
            - 'KB_ADDRESS_RETRIEVE=http://sf-kb:8890/sparql'
            - 'DR_ADDRESS=http://dr-api:8080/DataReceiver/webresources/'   

volumes:
  sf-config:
    external: true   
  kb_db:
    external: true
  sf-api_logs:
    external: true    
  dr-api_logs:
    external: true

networks:
  default:
    external:
      name: collnetwork
